'use client'

import React, { createContext, useContext, useState } from 'react'

type Language = 'en' | 'zh' | 'hi' | 'es' | 'ar' | 'fr' | 'pt' | 'ru' | 'id'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    signUp: 'Sign Up',
    login: 'Login',
    logout: 'Logout',
    profile: 'Profile',
    cart: 'Cart',
    // Hero
    title: 'Tropic Tech',
    subtitle: 'Workstation Rental Company',
    subtitle2: '5+ Years in Bali and Leading the Industry',
    rentNow: 'Rent Now',
    // Categories
    desks: 'Desks',
    monitors: 'Monitors',
    chairs: 'Chairs',
    keyboardMouse: 'Keyboard & Mouse',
    accessories: 'Accessories',
    // Product Card
    order: 'Order',
    daily: 'Daily',
    monthly: 'Monthly',
    // Order Popup
    orderPopup: 'Order',
    rentalDuration: 'Rental Duration',
    unitPrice: 'Unit Price',
    totalPrice: 'Total Price',
    currency: 'Currency',
    selectPaymentMethod: 'Select Payment Method',
    paypal: 'PayPal / EDC / Debit / Credit Card',
    stripe: 'Stripe / Crypto',
    whatsapp: 'Order via WhatsApp',
    formspree: 'Submit Order',
    cash: 'Cash',
    placeOrder: 'Place Order',
    cancel: 'Cancel',
    // Payment Methods
    selectCurrency: 'Select Currency',
    // Sections
    products: 'Products',
    packages: 'Packages',
    services: 'Services',
    faq: 'FAQ',
    aboutUs: 'About Us',
    reviews: 'Reviews',
    // Footer
    allRightsReserved: 'All Rights Reserved',
    getInTouch: 'Get in Touch',
    privacyPolicy: 'Privacy Policy',
    termsConditions: 'Terms & Conditions',
    refundPolicy: 'Refund Policy',
    credits: 'Design by indodesign.website | indonesianvisas.com | balihelp.id | mybisnis.app',
  },
  zh: {
    signUp: '注册',
    login: '登录',
    logout: '退出登录',
    profile: '个人资料',
    cart: '购物车',
    title: '热带科技',
    subtitle: '工作站租赁公司',
    subtitle2: '巴厘岛5年经验，行业领先',
    rentNow: '立即租赁',
    desks: '桌子',
    monitors: '显示器',
    chairs: '椅子',
    keyboardMouse: '键盘鼠标',
    accessories: '配件',
    order: '订购',
    daily: '每日',
    monthly: '每月',
    orderPopup: '订购',
    rentalDuration: '租赁期限',
    unitPrice: '单价',
    totalPrice: '总价',
    currency: '货币',
    selectPaymentMethod: '选择支付方式',
    paypal: 'PayPal / EDC / 借记卡 / 信用卡',
    stripe: 'Stripe / 加密货币',
    whatsapp: '通过 WhatsApp 订购',
    formspree: '提交订单',
    cash: '现金',
    placeOrder: '下单',
    cancel: '取消',
    selectCurrency: '选择货币',
    products: '产品',
    packages: '套餐',
    services: '服务',
    faq: '常见问题',
    aboutUs: '关于我们',
    reviews: '评价',
    allRightsReserved: '版权所有',
    getInTouch: '联系我们',
    privacyPolicy: '隐私政策',
    termsConditions: '条款与条件',
    refundPolicy: '退款政策',
    credits: '设计由 indodesign.website | indonesianvisas.com | balihelp.id | mybisnis.app',
  },
  hi: {
    signUp: 'साइन अप',
    login: 'लॉग इन',
    logout: 'लॉग आउट',
    profile: 'प्रोफाइल',
    cart: 'कार्ट',
    title: 'ट्रॉपिक टेक',
    subtitle: 'वर्कस्टेशन रेंटल कंपनी',
    subtitle2: 'बाली में 5+ वर्ष और उद्योग में अग्रणी',
    rentNow: 'अभी किराए पर लें',
    desks: 'डेस्क',
    monitors: 'मॉनिटर',
    chairs: 'कुर्सियाँ',
    keyboardMouse: 'कीबोर्ड और माउस',
    accessories: 'सामान',
    order: 'ऑर्डर करें',
    daily: 'दैनिक',
    monthly: 'मासिक',
    orderPopup: 'ऑर्डर',
    rentalDuration: 'किराये की अवधि',
    unitPrice: 'इकाई मूल्य',
    totalPrice: 'कुल मूल्य',
    currency: 'मुद्रा',
    selectPaymentMethod: 'भुगतान विधि चुनें',
    paypal: 'PayPal / EDC / डेबिट / क्रेडिट कार्ड',
    stripe: 'Stripe / क्रिप्टो',
    whatsapp: 'WhatsApp से ऑर्डर करें',
    formspree: 'ऑर्डर सबमिट करें',
    cash: 'नकद',
    placeOrder: 'ऑर्डर दें',
    cancel: 'रद्द करें',
    selectCurrency: 'मुद्रा चुनें',
    products: 'उत्पाद',
    packages: 'पैकेज',
    services: 'सेवाएं',
    faq: 'सामान्य प्रश्न',
    aboutUs: 'हमारे बारे में',
    reviews: 'समीक्षाएं',
    allRightsReserved: 'सर्वाधिकार सुरक्षित',
    getInTouch: 'संपर्क करें',
    privacyPolicy: 'गोपनीयता नीति',
    termsConditions: 'नियम और शर्तें',
    refundPolicy: 'धनवापसी नीति',
    credits: 'डिजाइन indodesign.website | indonesianvisas.com | balihelp.id | mybisnis.app द्वारा',
  },
  es: {
    signUp: 'Registrarse',
    login: 'Iniciar sesión',
    logout: 'Cerrar sesión',
    profile: 'Perfil',
    cart: 'Carrito',
    title: 'Tropic Tech',
    subtitle: 'Empresa de Alquiler de Estaciones de Trabajo',
    subtitle2: '5+ Años en Bali y Líder en la Industria',
    rentNow: 'Alquilar Ahora',
    desks: 'Escritorios',
    monitors: 'Monitores',
    chairs: 'Sillas',
    keyboardMouse: 'Teclado y Ratón',
    accessories: 'Accesorios',
    order: 'Ordenar',
    daily: 'Diario',
    monthly: 'Mensual',
    orderPopup: 'Ordenar',
    rentalDuration: 'Duración del Alquiler',
    unitPrice: 'Precio Unitario',
    totalPrice: 'Precio Total',
    currency: 'Moneda',
    selectPaymentMethod: 'Seleccionar Método de Pago',
    paypal: 'PayPal / EDC / Débito / Crédito',
    stripe: 'Stripe / Cripto',
    whatsapp: 'Ordenar por WhatsApp',
    formspree: 'Enviar Orden',
    cash: 'Efectivo',
    placeOrder: 'Realizar Pedido',
    cancel: 'Cancelar',
    selectCurrency: 'Seleccionar Moneda',
    products: 'Productos',
    packages: 'Paquetes',
    services: 'Servicios',
    faq: 'Preguntas Frecuentes',
    aboutUs: 'Sobre Nosotros',
    reviews: 'Reseñas',
    allRightsReserved: 'Todos los Derechos Reservados',
    getInTouch: 'Contáctanos',
    privacyPolicy: 'Política de Privacidad',
    termsConditions: 'Términos y Condiciones',
    refundPolicy: 'Política de Reembolso',
    credits: 'Diseño por indodesign.website | indonesianvisas.com | balihelp.id | mybisnis.app',
  },
  ar: {
    signUp: 'التسجيل',
    login: 'تسجيل الدخول',
    logout: 'تسجيل الخروج',
    profile: 'الملف الشخصي',
    cart: 'السلة',
    title: 'تروبيك تك',
    subtitle: 'شركة تأجير محطات العمل',
    subtitle2: '5+ سنوات في بالي والريادة في المجال',
    rentNow: 'أجر الآن',
    desks: 'مكاتب',
    monitors: 'شاشات',
    chairs: 'كراسي',
    keyboardMouse: 'لوحة المفاتيح والماوس',
    accessories: 'ملحقات',
    order: 'طلب',
    daily: 'يومي',
    monthly: 'شهري',
    orderPopup: 'طلب',
    rentalDuration: 'مدة التأجير',
    unitPrice: 'السعر الوحدوي',
    totalPrice: 'السعر الإجمالي',
    currency: 'العملة',
    selectPaymentMethod: 'اختر طريقة الدفع',
    paypal: 'PayPal / EDC / خصم بطاقة / بطاقة ائتمان',
    stripe: 'Stripe / تشفير',
    whatsapp: 'طلب عبر واتساب',
    formspree: 'إرسال الطلب',
    cash: 'نقدًا',
    placeOrder: 'تقديم الطلب',
    cancel: 'إلغاء',
    selectCurrency: 'اختر العملة',
    products: 'المنتجات',
    packages: 'الباقات',
    services: 'الخدمات',
    faq: 'الأسئلة الشائعة',
    aboutUs: 'من نحن',
    reviews: 'التقييمات',
    allRightsReserved: 'جميع الحقوق محفوظة',
    getInTouch: 'تواصل معنا',
    privacyPolicy: 'سياسة الخصوصية',
    termsConditions: 'الشروط والأحكام',
    refundPolicy: 'سياسة الاسترداد',
    credits: 'التصميم بواسطة indodesign.website | indonesianvisas.com | balihelp.id | mybisnis.app',
  },
  fr: {
    signUp: "S'inscrire",
    login: 'Connexion',
    logout: 'Déconnexion',
    profile: 'Profil',
    cart: 'Panier',
    title: 'Tropic Tech',
    subtitle: 'Société de Location de Postes de Travail',
    subtitle2: '5+ Ans à Bali et Leader de l\'Industrie',
    rentNow: 'Louer Maintenant',
    desks: 'Bureaux',
    monitors: 'Moniteurs',
    chairs: 'Chaises',
    keyboardMouse: 'Clavier et Souris',
    accessories: 'Accessoires',
    order: 'Commander',
    daily: 'Quotidien',
    monthly: 'Mensuel',
    orderPopup: 'Commander',
    rentalDuration: 'Durée de Location',
    unitPrice: 'Prix Unitaire',
    totalPrice: 'Prix Total',
    currency: 'Devise',
    selectPaymentMethod: 'Sélectionner le Mode de Paiement',
    paypal: 'PayPal / EDC / Débit / Crédit',
    stripe: 'Stripe / Crypto',
    whatsapp: 'Commander via WhatsApp',
    formspree: 'Soumettre la Commande',
    cash: 'Espèces',
    placeOrder: 'Passer la Commande',
    cancel: 'Annuler',
    selectCurrency: 'Sélectionner la Devise',
    products: 'Produits',
    packages: 'Forfaits',
    services: 'Services',
    faq: 'FAQ',
    aboutUs: 'À Propos de Nous',
    reviews: 'Avis',
    allRightsReserved: 'Tous Droits Réservés',
    getInTouch: 'Contactez-nous',
    privacyPolicy: 'Politique de Confidentialité',
    termsConditions: 'Conditions Générales',
    refundPolicy: 'Politique de Remboursement',
    credits: 'Design par indodesign.website | indonesianvisas.com | balihelp.id | mybisnis.app',
  },
  pt: {
    signUp: 'Cadastrar-se',
    login: 'Entrar',
    logout: 'Sair',
    profile: 'Perfil',
    cart: 'Carrinho',
    title: 'Tropic Tech',
    subtitle: 'Empresa de Aluguel de Estações de Trabalho',
    subtitle2: '5+ Anos em Bali e Líder na Indústria',
    rentNow: 'Alugar Agora',
    desks: 'Mesas',
    monitors: 'Monitores',
    chairs: 'Cadeiras',
    keyboardMouse: 'Teclado e Mouse',
    accessories: 'Acessórios',
    order: 'Pedir',
    daily: 'Diário',
    monthly: 'Mensal',
    orderPopup: 'Pedir',
    rentalDuration: 'Duração do Aluguel',
    unitPrice: 'Preço Unitário',
    totalPrice: 'Preço Total',
    currency: 'Moeda',
    selectPaymentMethod: 'Selecionar Método de Pagamento',
    paypal: 'PayPal / EDC / Débito / Crédito',
    stripe: 'Stripe / Cripto',
    whatsapp: 'Pedir via WhatsApp',
    formspree: 'Enviar Pedido',
    cash: 'Dinheiro',
    placeOrder: 'Fazer Pedido',
    cancel: 'Cancelar',
    selectCurrency: 'Selecionar Moeda',
    products: 'Produtos',
    packages: 'Pacotes',
    services: 'Serviços',
    faq: 'Perguntas Frequentes',
    aboutUs: 'Sobre Nós',
    reviews: 'Avaliações',
    allRightsReserved: 'Todos os Direitos Reservados',
    getInTouch: 'Entre em Contato',
    privacyPolicy: 'Política de Privacidade',
    termsConditions: 'Termos e Condições',
    refundPolicy: 'Política de Reembolso',
    credits: 'Design por indodesign.website | indonesianvisas.com | balihelp.id | mybisnis.app',
  },
  ru: {
    signUp: 'Регистрация',
    login: 'Войти',
    logout: 'Выйти',
    profile: 'Профиль',
    cart: 'Корзина',
    title: 'Tropic Tech',
    subtitle: 'Компания по аренде рабочих станций',
    subtitle2: '5+ лет на Бали и лидер в отрасли',
    rentNow: 'Арендовать',
    desks: 'Столы',
    monitors: 'Мониторы',
    chairs: 'Стулья',
    keyboardMouse: 'Клавиатура и мышь',
    accessories: 'Аксессуары',
    order: 'Заказать',
    daily: 'Дневной',
    monthly: 'Месячный',
    orderPopup: 'Заказ',
    rentalDuration: 'Срок аренды',
    unitPrice: 'Цена за единицу',
    totalPrice: 'Общая цена',
    currency: 'Валюта',
    selectPaymentMethod: 'Выберите способ оплаты',
    paypal: 'PayPal / EDC / Дебетовая / Кредитная карта',
    stripe: 'Stripe / Криптовалюта',
    whatsapp: 'Заказ через WhatsApp',
    formspree: 'Отправить заказ',
    cash: 'Наличные',
    placeOrder: 'Оформить заказ',
    cancel: 'Отмена',
    selectCurrency: 'Выберите валюту',
    products: 'Товары',
    packages: 'Пакеты',
    services: 'Услуги',
    faq: 'ЧАВО',
    aboutUs: 'О нас',
    reviews: 'Отзывы',
    allRightsReserved: 'Все права защищены',
    getInTouch: 'Свяжитесь с нами',
    privacyPolicy: 'Политика конфиденциальности',
    termsConditions: 'Условия использования',
    refundPolicy: 'Политика возврата',
    credits: 'Дизайн indodesign.website | indonesianvisas.com | balihelp.id | mybisnis.app',
  },
  id: {
    signUp: 'Daftar',
    login: 'Masuk',
    logout: 'Keluar',
    profile: 'Profil',
    cart: 'Keranjang',
    title: 'Tropic Tech',
    subtitle: 'Perusahaan Penyewahan Alat-alat Bekerja',
    subtitle2: '5+ Tahun di Bali dan Terdepan di Bidangnya',
    rentNow: 'Sewa Sekarang',
    desks: 'Meja',
    monitors: 'Monitor',
    chairs: 'Kursi',
    keyboardMouse: 'Keyboard dan Mouse',
    accessories: 'Aksesoris',
    order: 'Pesan',
    daily: 'Harian',
    monthly: 'Bulanan',
    orderPopup: 'Pesan',
    rentalDuration: 'Durasi Sewa',
    unitPrice: 'Harga Satuan',
    totalPrice: 'Harga Total',
    currency: 'Mata Uang',
    selectPaymentMethod: 'Pilih Metode Pembayaran',
    paypal: 'PayPal / EDC / Debit / Kartu Kredit',
    stripe: 'Stripe / Kripto',
    whatsapp: 'Pesan via WhatsApp',
    formspree: 'Kirim Pesanan',
    cash: 'Tunai',
    placeOrder: 'Buat Pesanan',
    cancel: 'Batal',
    selectCurrency: 'Pilih Mata Uang',
    products: 'Produk',
    packages: 'Paket',
    services: 'Layanan',
    faq: 'FAQ',
    aboutUs: 'Tentang Kami',
    reviews: 'Ulasan',
    allRightsReserved: 'Hak Cipta Dilindungi',
    getInTouch: 'Hubungi Kami',
    privacyPolicy: 'Kebijakan Privasi',
    termsConditions: 'Syarat & Ketentuan',
    refundPolicy: 'Kebijakan Pengembalian',
    credits: 'Desain oleh indodesign.website | indonesianvisas.com | balihelp.id | mybisnis.app',
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const languageNames: Record<Language, string> = {
  en: 'English',
  zh: '中文',
  hi: 'हिन्दी',
  es: 'Español',
  ar: 'العربية',
  fr: 'Français',
  pt: 'Português',
  ru: 'Русский',
  id: 'Bahasa Indonesia',
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en')

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return { ...context, languageNames }
}
